export function permisosPorRol(rol: string): string[] {
  const defaults: Record<string, string[]> = {
    owner: [
      'dashboard',
      'votantes',
      'crm',
      'peticiones',
      'eventos',
      'mapa',
      'boletines',
      'llamadas',
      'candidato',
      'encuestas',
      'casillas',
      'monitoreo',
      'proyeccion',
      'ficha_seccional',
      'historico_electoral',
      'inteligencia_electoral',
      'opositores',
      'data',
      'usuarios',
      'app_brigada',
    ],
    candidato: [
      'dashboard',
      'votantes',
      'crm',
      'peticiones',
      'eventos',
      'mapa',
      'boletines',
      'llamadas',
      'candidato',
      'encuestas',
      'casillas',
      'monitoreo',
      'proyeccion',
      'ficha_seccional',
      'historico_electoral',
      'inteligencia_electoral',
      'opositores',
      'data',
      'usuarios',
      'app_brigada',
    ],
    coord_general: [
      'dashboard',
      'votantes',
      'crm',
      'peticiones',
      'eventos',
      'mapa',
      'boletines',
      'llamadas',
      'encuestas',
      'casillas',
      'monitoreo',
      'proyeccion',
      'ficha_seccional',
      'historico_electoral',
      'inteligencia_electoral',
      'opositores',
      'data',
      'app_brigada',
    ],
    coord_zona: [
      'dashboard',
      'votantes',
      'crm',
      'peticiones',
      'eventos',
      'mapa',
      'encuestas',
      'casillas',
      'monitoreo',
      'ficha_seccional',
      'app_brigada',
    ],
    brigadista: ['app_brigada'],
    cm: [
      'dashboard',
      'crm',
      'peticiones',
      'boletines',
      'candidato',
      'encuestas',
      'monitoreo',
      'proyeccion',
      'ficha_seccional',
      'historico_electoral',
      'inteligencia_electoral',
      'opositores',
      'data',
    ],
    encargado_peticiones: [
      'dashboard',
      'peticiones',
      'votantes',
      'crm',
      'mapa',
      'encuestas',
      'monitoreo',
      'ficha_seccional',
    ],
    superadmin: ['admin'],
  };
  return defaults[rol] || [];
}

export function puedeAcceder(
  permisos: string[] | null | undefined,
  seccion: string,
  rol?: string,
): boolean {
  const efectivos = Array.isArray(permisos) ? permisos : [];
  if (efectivos.length === 0) {
    const fallback = rol ? permisosPorRol(rol) : [];
    return fallback.includes(seccion);
  }
  return efectivos.includes(seccion);
}
